-keepattributes SourceFile,LineNumberTable
-keep class net.elparadisogonzalo.terminal.** { *; }
-keep class com.termux.terminal.** { *; }
-keep class com.termux.view.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn org.conscrypt.**
